# Generated by Django 5.0.6 on 2024-07-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("biografia", models.TextField()),
                ("nacionalidade", models.CharField(max_length=30)),
                ("data_nascimento", models.DateField()),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="funcionarios.dadosfuncionario",
                    ),
                ),
            ],
        ),
    ]
