# Generated by Django 5.0.6 on 2024-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="foto_autor",
            field=models.ImageField(default="autores/default.jpg", upload_to="autores"),
        ),
    ]
