# Generated by Django 5.0.7 on 2024-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0002_editora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="foto_autor",
            field=models.ImageField(upload_to="autores"),
        ),
        migrations.AlterField(
            model_name="editora",
            name="foto_editora",
            field=models.ImageField(upload_to="editoras"),
        ),
    ]
