# Generated by Django 5.0.6 on 2024-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0002_autor_foto_autor"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outros")],
                default="O",
                max_length=10,
            ),
        ),
    ]
