# Generated by Django 5.0.6 on 2024-07-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0003_autor_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Editora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("endereco", models.CharField(max_length=255)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("site", models.URLField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_atualizacao", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
