# Generated by Django 5.0.6 on 2024-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0004_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="foto_editora",
            field=models.ImageField(
                default="editoras/default.jpg", upload_to="editoras"
            ),
        ),
    ]
