# Generated by Django 5.0.6 on 2024-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0005_editora_foto_editora"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="data_ultima_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
