# Generated by Django 5.0.7 on 2024-07-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livros", "0009_alter_livro_numero_amostras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="livro",
            name="generos",
            field=models.ManyToManyField(related_name="livros", to="livros.genero"),
        ),
    ]
